title: Project Cobalt Blog
description: Updates and announcements from Project Cobalt
baseurl: "/cobalt"
url: "https://gobeyondidentity.github.io"
theme: minima

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
