title: Project Cobalt Blog
description: Updates and announcements from Project Cobalt
baseurl: "/cobalt"
url: "https://gobeyondidentity.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Excerpt settings
excerpt_separator: "\n\n"
